### ISSUE TITLE
Select element value change patch

### ISSUE THREAD

**Issue by mmnosek** [PuppetJs/PuppetJs#106]
I've created couple of html `<select>` elements recently and figure out that the moment when select value patch is send to the server should be different.
### Steps to reproduce
1. Create some `<select>` element binded to the property on the server
2. Open the chrome console and create change event listener breakpoint
3. Open network tab and select WS connection to watch patches
4. Change a value in a select element
### Expected result

Patch should be calculated and send right after `onchange` event is triggered 
### Actual result

`onchange` event is fired immediately, but there is no patch generated. Patch is generated after `<select>` element is unfocused (blurred)
### Affected browsers

**Chrome 53.0.2785**

On Safari and Firefox work as expected.

cc @tomalec

**Comment by tomalec** [comment]
Could you provide the versions (Starcounter, puppetjs, jsonpatch, polymer)
that you are using?

I'm affraid it may be related to asynchronicity of jsonpatch dirtychecking,
as recently I've changed jsonpatch to observe on key/mouse down.

Anyway, I would hold any more complicated fixes untill we will check it
with Polymer 2.0 to avoid regression. Alternatively, you can write
automated test for it.

**Comment by Mnosek** [comment]
I was hit by that issue once again. I have no idea for any workaround for that. Don't want to wait for Polymer 2.0 :) 

Let's say, that I have a list of items that will be presented at some report. I need to choose what elements should be visible on report. I would like to achieve it by filtering list by values in select (I think that it's very common usecase). User expects results to be changed right after he has changed a value inside `select` but nothing happens. After that user decides to create report, and result inside will be different that on the screen. Patch with new value will be applied just after any other click.

> Anyway, I would hold any more complicated fixes untill we will check it
with Polymer 2.0 to avoid regression

Can you check/Have you checked how it works in 2.0 preview?

> Alternatively, you can write automated test for it.

Can you extend your thougth? How the test will help in my case?

Versions:
Starcounter v2.3.0.4787
PuppetJs v2.2.1
JsonPatch v1.1.1
Polymer v1.7.0

**Comment by tomalec** [comment]
Sorry, but I didn't reproduce it earlier.

I have just checked with `/PuppetJs/lab/polymer/`
```
<select value="{{model.user.firstName$::change}}">
    <option>Albert</option>
    <option>Nikola</option>
</select>
```

And it seems to work (triggers request)

**Comment by tomalec** [comment]
> Can you check/Have you checked how it works in 2.0 preview?

I have checked how our binding works wit 2.0-preview few weeks ago, and I stopped befor complicated cases due to bug I have found and fixed, PRs are now merged, so I would need to check once agian.

It would be cool to have short code sample to check against.

> Can you extend your thougth? How the test will help in my case?

Test would help in my case ;) as I would have an easy way to reproduce and isolate the problem. Plus, it will help in your case as such issue should never get re-introduced

**Comment by Mnosek** [comment]
> And it seems to work (triggers request)
Do you mean that it works?

Steps to reproduce it in KitchenSink:
- Open KitchenSink/Dropdown
- In first select change "Dogs" to "Cats"
- Until you unfocus select you've just change "You like dogs" instead of "Cats"

**Comment by Mnosek** [comment]
Could you please check on OSX? We've just discovered that problem exists only on my mac... :)

**Comment by Mnosek** [comment]
I mean Chrome on OSX.

**Comment by warpech** [comment]
This is fault of Chrome or macOS.

See this fiddle: https://jsfiddle.net/cog1fq12/3/

**Comment by Mnosek** [comment]
OSX:
![events-chromeosx](https://cloud.githubusercontent.com/assets/4943949/20567251/51a54a0a-b198-11e6-97eb-c72d76df02d5.png)

Windows:
![events-chromewin](https://cloud.githubusercontent.com/assets/4943949/20567250/51a30380-b198-11e6-83fb-b3aac202ec7d.png)

There is missing mouseup event on OSX, so no dirtychecking.

**Comment by warpech** [comment]
@tomalec WDYT? should we add "change" event observer to JSON-Patch dirty checking? I don't see a better way to fix this.

**Comment by tomalec** [comment]
Me neither :( so it seems we'll revert back to old set of listeners..  I'll chceck if ther are any spec related bugs. So maybe one day it will get consistent.

By that time we will need automated test for it and pretty bold code comment :)

**Comment by tomalec** [comment]
I have created an issue on Chromium issue tracker https://bugs.chromium.org/p/chromium/issues/detail?id=668310
So now I see no other way than to add `change` listener.

**Comment by tomalec** [comment]
Or maybe, it's the time to start Proxy implementation? Especially that we agreed on finishing IE 11 support? http://kangax.github.io/compat-table/es6/

**Comment by warpech** [comment]
PR waiting for the review (link above)

**Comment by warpech** [comment]
@tomalec since https://github.com/Starcounter-Jack/JSON-Patch/pull/133 is now released, could you please update it in Starcounter `develop`?

**Comment by tomalec** [comment]
Sure, will do so.

**Comment by tomalec** [comment]
@mmnosek Could you check if it works for you in full app environment?

**Comment by mmnosek** [comment]
@tomalec absolutely works! Thanks guys for changes. Closing now.
