### ISSUE TITLE
<puppet-client> in iOS does not work

### ISSUE THREAD

**Issue by mattiasmak** [PuppetJs/PuppetJs#107]
We at colabers get this error when including <puppet-client> in our code:

this.createShadowRoot is not a function

It's hard to get more information. Will make en effort to reproduce.

**Comment by mattiasmak** [comment]
When using webcomponent.js instead of webcomponent-lite.js we get even more and stranger errors. 
Example: window.ShadowDOMPolyfill -> undefined is not an object (evaluating 'descriptor.value')
Only triggered when using puppet.
So error may not be puppet itself, rather dependencies
Yes, we use latest version of webcomponents.

**Comment by warpech** [comment]
@mattiasmak has presented this to me on Hangouts. I will try to fix it ASAP, though I need to get hold of an iOS device first.

This is not reproducible with Mac/Safari, but is 100% reproducible with iOS/Safari (current version).

**Comment by warpech** [comment]
Potential hint: one of the exceptions appears when some JS code is trying to call `Window.showModalDialog()`

**Comment by warpech** [comment]
> Potential hint: one of the exceptions appears when some JS code is trying to call Window.showModalDialog()

I cannot find anything in our or your code that calls `showModalDialog`. 

@mattiasmak I wonder where did that one particular `showModalDialog` error come from? Can you paste the full stack trace?

**Comment by mattiasmak** [comment]
Solution: window.showModalDialog = function(){};

Since getOwnPropertyNames(window) return showModalDialog, but is undefined. This causes webcomponents.js to throw an error. 

So until problem is solved in iOS webkit window.showModalDialog = function(){}; should do it.

**Comment by warpech** [comment]
I am unassigning myself for now. I don't think that we should hardcode this workaround in PuppetJs. For now, it is fine to paste this snippet somewhere in Starcounter app code. It might be fixed by Polymer 2.0, webcomponents.js v1

**Comment by tomalec** [comment]
It seems that it was a bug in webcomponents.js https://github.com/webcomponents/webcomponentsjs/issues/617
which is now fixed and merged to the new version.

**Comment by tomalec** [comment]
Fixed by upgrading polyfill, please let us know if you still have any problems.
