### ISSUE TITLE
Patches stop being applied

### ISSUE THREAD

**Issue by malx122** [PuppetJs/PuppetJs#108]
Hi!
Now and then, our application stop responding on patches from the server. (Havn't found any way of getting there consistent). There is no errors or warnings that can be seen in console and the connection seems fine.

Last time I decided to see what happened and I can see that puppet both sending and receiving patches. What it do not do is applying the patches. The puppetjs `validateAndApplySequence` is never called at all. There somewhere I was lost in the code since it was supposed to be called from `JSONPatchQueueSynchronous` ?

Can it be that it can reach a state where the `_ver#c$` or `_ver#s$` fails, maybe a timing issue? I forgot to check before I accidently dropped out of the session.

**Comment by malx122** [comment]
Yepp, it is a timing issue. (Lot easier to repeat on a slow server, with much data)
Seems like new Get request to the server before a response has been received triggers this.

**Comment by malx122** [comment]
I was told to close this one because the error is at the server side (starcounter). However, I'm not totally sure I'm ready to do this. Yes, It should be fixed at the server, but should'nt puppet somehow telling the server that it misses som messages as well? Can you always be sure that no data is lost in cyberspace? (That is an actual question, I have no idea if the used internet protocol includes this).

I also thinks that the client should somehow notify that something is wrong. Yes, receiving message in wrong order might not be wrong but when you continously get more and more messages without getting the lost one you know that something is wrong.

**Comment by warpech** [comment]
It is a PuppetJs issue, but we discuss it here: https://github.com/Starcounter/Starcounter/issues/3981

Closing as duplicate.
