### ISSUE TITLE
Patch and morphUrl is not sent in the correct order

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#15]
Yesterday, @malx122 showed me an issue where in a custom element's click handler he manipulates the data model and then calls Puppet's `morphUrl`.

Expected result is that the data model change is sent before GET request initiated by `morphUrl`.

Actual result is that the GET request for `morphUrl` is sent before the patch, so it results in incorrect state.

**Comment by miyconst** [comment]
@warpech, I have checked this scenario in PuppetJs/lab/Polymer and it works fine for me:

```html
<a href="index.html" onclick="getModel(document.querySelector('button')).user.resetNameClicked$ = true">
    Albert <strong>Einstein</strong>
</a>
```

`resetNameClicked$` sets value to *Isaac Newton* and morph to `index.html` sets value to *Albert Einstein*.

There are two requests in debugger:
1. `resetNameClicked$`.
2. Morph `index.html`.

In the result I see *Albert Einstein* not *Isaac Newton*, which is correct.

**Comment by warpech** [comment]
Closing as fixed
