### ISSUE TITLE
WebSocket disconnection should not be a fatal error

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#37]
In any of the following cases:
1) user loses Wi-Fi range
2) user puts his laptop to sleep/hibernation
3) server restarts
4) server stops

The users get's an alert about WebSocket disconnection:

![screenshot 2015-02-04 22 54 36](https://cloud.githubusercontent.com/assets/566463/6050591/3d9db08e-acc1-11e4-8521-6ccaaa8230e4.png)

This should not be an error because it is possible that the server was restarted but the session will be kept between the restarts. The next Puppet operation should try to reconnect to WebSocket or use HTTP fallback.

**Comment by warpech** [comment]
@miyconst after doing current work, could you investigate this and propose changes?

**Comment by miyconst** [comment]
Me and @warpech on skype call agreed to:

1. Disable the ugly error message.
2. Switch to http/json+patch if WebSocket connection drops.
3. Try to restore WebSocket connection in 5/10/20/40/80 seconds.
4. Display a small and not annoying icon when connection drops and hide the icon when connection restored.

**Comment by miyconst** [comment]
I have played with restoring WS connection a little bit. Now facing such problem:

1. Client loads page.
2. Client establishes connection with server.
3. Client sends patch 1 to the server.
4. Server receives the patch and closes the connection (or connection drops).
5. Client establishes connection with server again.
6. Client sends patch 2 to the server.
7. Server responds with remote version 3, but client expects it to be 2, as patch 1 was sent, but not confirmed.

What to do in such situation? We may ask server whether the patch 1 was really received or may assume by version # that the patch was received.

**Comment by tomalec** [comment]
Could you specify the versions that your are talking about in each step? - PuppetJS' local version == Server's remote vs. PuppetJS' remote version == Server's remote? (`/_ClientVersion` or `/_ServerVersion$` )

**Comment by miyconst** [comment]
1.1.  Out:
```js
this.localVersion = 1;
this.remoteVersion = 1;
```
```json
[{"op":"replace","path":"/_ver#c$","value":2},{"op":"test","path":"/_ver#s","value":1},{"op":"replace","path":"/workspaces/0/Images/CurrentPage/Images/Cancel$","value":1}]
```

1.2. In: none
```js
this.localVersion = 2;
this.remoteVersion = 1;
```

2.1. Out:
```js
this.localVersion = 2;
this.remoteVersion = 1;
```

```json
[{"op":"replace","path":"/_ver#c$","value":3},{"op":"test","path":"/_ver#s","value":1},{"op":"replace","path":"/workspaces/0/Images/CurrentPage/Images/Save$","value":1}]
```

2.2. In: 
```js
this.localVersion = 3;
this.remoteVersion = 1;
```

```json
[{"op":"replace","path":"/_ver#s","value":3},{"op":"test","path":"/_ver#c$","value":3},{"op":"replace","path":"/workspaces/0/Images/CurrentPage/Images/RedirectUrl$","value":"/images"}]
```

At this moment local `remoteVersion` is `1`, but the one which come from the server is `3`.

**Comment by miyconst** [comment]
Ping @warpech and @tomalec.

**Comment by tomalec** [comment]
So the connections gets closed after browser sent message, and after server received it, but before server responses to browser, and what is worse server did composed change to clients message, which was not send.

@chrhol chould you confirm, I would expect that server ma queue such pending change on server side, and either send it when reconnected, on will just send entire JSON to reset all versions

**Comment by miyconst** [comment]
If it may help somehow:

```csharp
void Handle(Input.Cancel Action) {
    WebSocket.Current.Disconnect();
}
```

This is how I close the connection on `Cancel` button press.

**Comment by warpech** [comment]
I rewrote Konstantin's problem including the version numbers, because I couldn't put my head around it:

1. Client loads page (`_ver#c$: 0, _ver#s: 0`)
2. Client establishes connection with server
3. Client sends patch 1 to the server  (`_ver#c$: 1, _ver#s: 0`)
4. Server receives the patch and closes the connection (or connection drops).
5. Client establishes connection with server again.
6. Client sends patch 2 to the server   (`_ver#c$: 2, _ver#s: 0`)
7. Server responds with (`_ver#c$: 2, _ver#s: 2`), but client still waits for `_ver#s: 1`. In result, client hangs indefinitely

A naive solution would be to time out and create a new request for the missing patch or just the current viewmodel.

But maybe there could be some pure-OT solution?

**Comment by miyconst** [comment]
Only one correction:
7. Client does not hand, it throws an exception.

**Comment by warpech** [comment]
What is the exception message?

**Comment by tomalec** [comment]
Pure OT solution would be that server responds with `{op: "replace", path: "_ver#s", value: "1"}` at 7.

**Comment by warpech** [comment]
Why? Because in step 6 the client said that it knows `_ver#s: 0`?

**Comment by miyconst** [comment]
>What is the exception message?

My bad, it actually hangs, the exception occurs if the received patch was already applied.

**Comment by tomalec** [comment]
@warpech  because versions should be increased consecutively, and I se no `{op: "replace", path: "_ver#s", value: "1"}` in this flow.

**Comment by warpech** [comment]
I think that in Konstantin's case it is true that server closed the connection imperatively, which means that it SHOULD push the pending `_ver#s: 1` patch before disconnection. If it doesn't do that then it is an error.

But what in case when the server increased `_ver#s` to 1, but that patch never reached the client, because it was eaten by the gateway, middleware, etc. How could we recover from that?

**Comment by chrhol** [comment]
> But what in case when the server increased _ver#s to 1, but that patch never reached the client, because it was eaten by the gateway, middleware, etc. How could we recover from that?

This is a good point. I think the client, when reconnecting, either need to ask the server for all patches from a version or just asks for the whole viewmodel. for the first option, we need to save all patches that the client have not confirmed that it have received.

**Comment by tomalec** [comment]
> the client, when reconnecting, either need to ask the server for all patches from a version or just asks for the whole viewmodel. for the first option, we need to save all patches that the client have not confirmed that it have received.

Totally agreed, as I mentioned, [JSON Patch OT Agent ](https://github.com/PuppetJs/JSON-Patch-OT-agent) keeps a list of "pending" patches - patches that were send to the remote, but remote didn't confirm it get them.

So I would say that both peers should send such info to each other when re-connecting.

----

> But what in case when the server increased _ver#s to 1, but that patch never reached the client, because it was eaten by the gateway, middleware, etc. How could we recover from that?

I don't think PuppetJs should solve the problem of someone filtering, and eating messages during communication.

Our working scenarios are:
## A
0. client sends a patch that triggers a change on server,
1. server increases `_ver#s` to 1, and sends it to client,
2. server closes connection,
3. once connection is re-opened (server may return view-model with `_ver#s==1`),
4. if a change is made on server-side, server increases `_ver#s` to 2, and sends it to client.

## B
0. client sends a patch that triggers a change on server,
2. server closes connection, and no change was made,
3. once connection is re-opened (server may return view-model with `_ver#s==1`),
4. if a change is made on server-side, server increases `_ver#s` to 1, and sends it to client.

**Comment by warpech** [comment]
> I don't think PuppetJs should solve the problem of someone filtering, and eating messages during communication also.

So you say PuppetJs should not solve the problem but actually in C you propose a solution :) Or is it incomplete?

A problem that I see with point C7 is currently we treat is as an error: https://github.com/PuppetJs/JSON-Patch-Queue/blob/gh-pages/src/json-patch-queue.js#L61. We can change it to be a warning.

**Comment by tomalec** [comment]
> in C you propose a solution :) Or is it incomplete?
Yes i do. But this is not a solution for all missing messages, only for re-sending pending messages, so somehow extending existing feature.


It will not send an error for C7 as patches 1 and 4 are processed on server, but you are right if we have PuppetJS, and JSON-Patch-OT-agent.js working on server as well, it will be an error, as 1 was already applied, in such case we should make it as warning, and disregard the patch 1, and apply 4.

**Comment by miyconst** [comment]
Anything new in this issue? What is the priority?

**Comment by warpech** [comment]
Discussion about session reconnection is moved to another issue. Thanks for fixing the issue in topic!
