### ISSUE TITLE
Remove `beforeSend` callback or add it for WebSockets too

### ISSUE THREAD

**Issue by tomalec** [PuppetJs/PuppetJs#40]
Currently beforeSend callback is supported only for HTTP requests, but is not triggered for WebSocket `send`.

I think we should either remove it, or add it for WebSockets as well.
@warpech WDYT?

**Comment by warpech** [comment]
My Git log shows that beforeSend was added in commit 6d9a109899c9dcafb01d8927a2298f21dca0b2c6

> add beforeSend callback for hackability (one project uses puppet.xhr internally)

I found what was actually the application. I think that it can be removed now.

**Comment by tomalec** [comment]
I think hackability is still persevered, and after separation of network layer, we can achieve even more:
**beforeSend**:
```js
var oldSend = puppet.network.send; 
puppet.network.send = function(msg){
  beforeSend(msg);
  oldSend.call(puppet.network, msg);
}
```
**afterSend**:
```js
var oldSend = puppet.network.send; 
puppet.network.send = function(msg){
  oldSend.call(puppet.network, msg);
  afterSend(msg);
}
```

Maybe it's not nicest way, but as long as we do not see any real use case, I believe it's enough.

**Comment by warpech** [comment]
:+1:
