### ISSUE TITLE
Strict type mode

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#41]
PuppetJs should be able to keep the type of JSON properties. 

For example, in case a `number` property is bound to a `<input type="number">` with Polymer, a change of the value results in change of type to `string` (because all input values are strings in HTML).

PuppetJs should have a strict type mode in which it performs type casting before creating the outgoing patch.

This is point 7 from https://github.com/Starcounter/Starcounter/issues/2468 and point 2 from https://github.com/Starcounter/Starcounter/issues/2470

**Comment by miyconst** [comment]
@warpech, if this is an important issue, let's discuss how to implement it.

**Comment by warpech** [comment]
Yes it is still relevant, though not very urgent because the server deals with casting values to the desired type. I will be happy to review your suggestions on implementing it.

**Comment by miyconst** [comment]
I really don't know how that could be achieved without headache.

For example, the mode:
```json
{
    "Int": 0
}
```

The html:
```html
<input type="text" value="{{Int}}" />
<input type="number" value="{{Int}}" />
```

To what type the value should be cast?

We could remember first type of each property of the initial model, but how to deal with entire object replacement?

I think, that this problem should be solved on WebComponents level. If there is a component `date-picker`, which has three drop downs to select year/month/day, and four values: date/year/month/day, then it should transform values to desired type date/int/int/int before passing to the outside world.

**Comment by warpech** [comment]
Web Components are actually the reason this issue was created. On DOM level, Custom Element attribute values are always strings. Some clever frameworks do the type conversion, but it should be expected that a numeric value will be converted to string by the client side framework.

Could you do some research how client side frameworks that use HTML to define the view (Polymer 1.0, Angular, Knockout) address this issue? Maybe this can be solved on framework side, just as we decided with with [`onblur`](https://github.com/PuppetJs/PuppetJs/issues/23)

**Comment by miyconst** [comment]
## Polymer 1.x
Introduced property types, looks like this:
```js
properties: {
    obj: {
        type: Object,
        value: null
    },
    int: {
        type: Number,
        value: 11
    },
    str: {
        type: String,
        value: ""
    }
}
```
But the value still became string, if bound like this:
```html
<input type="number" value="{{int}}" />
```

## Angular
I don't have any experience with Angular, can investigate if needed though.

## KnockoutJs
All of the values bound  to input/select/textarea are converted to string, and sometimes it is very annoying.

**Comment by warpech** [comment]
So, in KnockoutJs there is no way to force type conversion? Can you investigate Angular? This confirms that we need to solve this at Puppet level

**Comment by miyconst** [comment]
KnockoutJs has `observable.subscribe` function, which fires each time new value set. The callback can be used to force strict type, but can't be used together with html binding, because it leads to an infinite loop.

```js
var o = ko.observable(1);

o.subscribe(function (newValue) {
    var int = parseInt(newValue);

    if (int !== newValue) {
        o(int);
    }
});
```
```html
<input type="checkbox" data-bind="value: o" />
```
After binding applied to the input, the value will be changed to `"1"`, but then callback fires and changes it back to `1`, and the loop starts again.

There is a workaround, something like this:

```js
var o = ko.observable();

o.int = ko.computed(function () {
    return parseInt(o());
});
```

The `o.int` will always be of type `Number` and will be automatically updated after `o` changes.

**Comment by miyconst** [comment]
AngularJs has some features, but also does not maintain original property type, here is a small playground: 
https://jsfiddle.net/79ftv1fy/

The features:
1. Converts incoming values from `<input type="number" />` to `Number`.
2. Newer version has a `convert-to-number` directive. https://docs.angularjs.org/api/ng/directive/select

**Comment by miyconst** [comment]
Ping @warpech.

**Comment by warpech** [comment]
As it turns out from your investigation (thanks a lot for that!), modern frameworks have a way to keep the type. I think we don't have to work on that then. If someone doesn't agree, please reopen.

For future consideration: Since this issue is related to keeping the intended structure of JSON, I propose that this should be solved using JSON Schema (similarly to https://github.com/PuppetJs/PuppetJs/issues/35).

For example this library has a `convert` method: https://github.com/litixsoft/lx-valid#convert-option

If we ever do JSON-Schema, it would be cool to do it as a PuppetJs extension, not to clutter the core.
