### ISSUE TITLE
CLOSED and CLOSING states of WebSocket are not covered

### ISSUE THREAD

**Issue by tomalec** [PuppetJs/PuppetJs#43]
So messages sent during that period may never reach the server, what with JSON Patch queuing enabled may block any further communication..

**Comment by warpech** [comment]
@miyconst after doing current work, could you investigate this and propose changes?

**Comment by miyconst** [comment]
Looks like yes, this situation may happen.

Those are the possible values for `Socket.readyState`:
>A value of 0 indicates that the connection has not yet been established.
A value of 1 indicates that the connection is established and communication is possible.
A value of 2 indicates that the connection is going through the closing handshake.
A value of 3 indicates that the connection has been closed or could not be opened.

Currently `PuppetNetworkChannel` establishes connection and sends a message in `onopen` if the state is equal to `0` or sends a message immediately in other case.

I suggest that we:

- [x] 0: establish connection and send message when callback is established.
- [ ] 1: send message.
- [ ] 2: add message to `onopen` queue.
- [ ] *: ~~send message.~~
- [ ] *: send message via http.

**Comment by warpech** [comment]
@tomalec - WDYT? 

The way I understand it, we have a choice to create yet another queue to store messages pending for WS (for me that is very undesired) or send patches over HTTP if WS is in other state than `1`.

**Comment by miyconst** [comment]
@warpech there is already a pseudo queue for outgoing messages over WebSocket, so using it won't create a new one, but I would also like to avoid it.

**Comment by warpech** [comment]
Where is that in code?

**Comment by tomalec** [comment]
@warpech  here: https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L168

@miyconst How your proposition differ from current implementation? 3 and 4 are just not implemented, right? So we would need just 2 more elsseifs at https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L177, wouldn't we?

**Comment by miyconst** [comment]
@tomalec, you are right, I thought we could just implement case 3 and 4.

**Comment by warpech** [comment]
Why not simplify it.

As I proposed on today's meeting, WS (re)connection should be maintained automatically in bootstrap (#59, #37) and therefore can be removed from `PuppetNetworkChannel.prototype.send`. 

`PuppetNetworkChannel.prototype.send` gets simplified to:

```js
PuppetNetworkChannel.prototype.send = function(msg){
    var that = this;
    if (this.useWebSocket && this._ws && this._ws.readyState === 1) {
        this._ws.send(msg);
        that.onSend(msg, that._ws.url, "WS");
    }
    else {
      var url = this.referer || this.remoteUrl;
      //"referer" should be used as the url when sending JSON Patches (see https://github.com/PuppetJs/PuppetJs/wiki/Server-communication)
      this.xhr(url, 'application/json-patch+json', msg, function (res, method) {
          that.onReceive(res.responseText, url, method);
        });
    }
    return this;
  };
```

**Comment by tomalec** [comment]
LGTM

**Comment by miyconst** [comment]
I also agree.

**Comment by miyconst** [comment]
@warpech should I do this one?

**Comment by miyconst** [comment]
Updated puppetJs, but it still does not work if ws connection drops, because of remote version mismatch issue described in here: https://github.com/PuppetJs/PuppetJs/issues/37#issuecomment-111513786

**Comment by miyconst** [comment]
@warpech can this issue be closed? For ws connection we have another issue.

**Comment by warpech** [comment]
Looks good, thanks!
