### ISSUE TITLE
Undefined value rises and error: No value found in patch.

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/PuppetJs#47]
Inside GoogleSignIn application I am trying to use 
```html
<polymer-cookie name="soauthtoken" id="GoogleSignInCookie" value="{{SignInAuthToken$}}">
</polymer-cookie>
```

If there is no such cookie the value will be undefined. This fires an exception:
```javascript
Uncaught Error: 1000 No value found in patch.
Patch: {"op":"replace","path":"/user/GoogleSignIn/SignInAuthToken$"}
```
In puppet.js on line 662.
https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L694

Whose error this is and how should it be fixed?

For now I fixed `<polymer-cookie>` to return empty string instead of undefined.

**Comment by tomalec** [comment]
It seems to be the same issue as #21, and it's related to the fact that `undefined` is not valid JSON value . See also:
https://github.com/Starcounter-Jack/JSON-Patch/pull/36
https://github.com/Starcounter-Jack/JSON-Patch/issues/32
https://github.com/Starcounter-Jack/JSON-Patch/issues/60

**Comment by miyconst** [comment]
@tomalec thank you.

I understand why it throws the exception and I have read the issues.
What should I do in this situation?

`puppet.js` has correct behaviour from JSON standard point of view.
`<polymer-cookie>` has correct behavoiur from its point of view - if the cookie is not defined then value is undefined.
Together they don't work.

Should I modify `<polymer-cookie>` which is third side element?
Or I should look for a workaround like wrap `<polymer-cookie>` inside another element or access value with javascript code instead of bindings?

**Comment by tomalec** [comment]
I would suggest a workaround with `null` value. It should be valid from JSON point of view, from Puppet, and hopefully from your app code as well.

In long term, we should provide clearly defined, consistent way to handle js object in fast-json-patch, provide tests for it, and close issues in https://github.com/Starcounter-Jack/JSON-Patch.
Then we should provide also well defined behavior for PuppetJS.

I believe we should not send JSON Patches that are not RFC compliant (contains `undefined`s), but PuppetJS could  handle not only pure JSON view models, but also plan JavaScript objects.
@warpech WDYT?

**Comment by miyconst** [comment]
@tomalec okay.

I have made a custom element `<so-polymer-cookie>` which converts `undefined` value into `null`.
Closing the issue.
