### ISSUE TITLE
Puppet used the wrong host/port.

### ISSUE THREAD

**Issue by andwah** [PuppetJs/PuppetJs#50]
My page is loaded from ```http://localhost:8080/test.html```

In the ```<body>``` onload()  i do this:

```javascript
new Puppet({ remoteUrl: "http://localhost:8181/mymodel"  });
```

Then in the puppet websocket upgrade it will use ```http://localhost:8080/...``` not ```http://localhost:8181``` that i was expecting.

Note: the ```Port``` number is not the same for the main page and the puppet

**Comment by warpech** [comment]
I think that the solution is to change the same line as #48, so I suggest to do them together.

**Comment by tomalec** [comment]
Right now it uses whatever was provided as `remoteUrl` (or `window.location`) and just switches the protocol to `ws:` (or `wss:` accordingly #48)
