### ISSUE TITLE
Demo does not work smoothly on IE and FF

### ISSUE THREAD

**Issue by tomalec** [PuppetJs/PuppetJs#52]
`jsonpatch.generate` generates `[]` on blur after changing the data.

**Comment by tomalec** [comment]
This issue is composed of three things:
1. the way `jsonpatch`  shims the `Object.observe`,
2. the way `Puppet` filters the changes (for blur) (to be moved to `PuppetDOM`)
3. suspected difference between browsers in timeline of `Object.observe`/shimmed callbacks and `blur` event callbacks

In case of editing field.

1. jsonpatch triggers periodically `dirtyCheck` which calls `generate`. What is important in this case, is fact that `generate` updates mirror object, and calls changed callback if needed.
2. Puppet when called via such callback, disregards patches if user is still editing (`update-on="blur"`).
 The mirror object is now equal to current `puppet.obj`, and patches list is removed.
3. In case of last change and blur
 1. chrome (native)
   1. Triggers observe callback, which disregards patch,
   2. Triggers blur callback, which calls `generate` once again, where native `Object.deliverChangeRecords` returns patch which was disregarded in point above.
 2. IE (shimmed)
   1. Triggers observe callback, which disregards patch,
   2. Triggers blur callback, which calls `generate` once again, which compares mirror to current object, and returns `[]`, as no new change was provided.
 3. Firefox (shimmed), usually behaves like native, but sometimes (when you put a break point, or heavy operation before last generate, ends up like IE.

Here is jsfiddle for that http://jsfiddle.net/tomalec/wt42L31a/


@warpech, I think we should not rely on such native behavior, even if `Object.observe` have special place in event loop, it could provide a huge confusion, and problems in maintenance.

Maybe we should delegate on-blur vs on-keyup feature to the client app?
Or create a separated custom-element/ library to support OnBlurTemplateBinding feature (and on batch as well https://github.com/PuppetJs/PuppetJs/issues/23)

**Comment by warpech** [comment]
Fixed the above in PuppetJs 1.1.0 by removing `blur` handling from PuppetDom. Now `blur` handling needs to be solved on view level (by the two-way binging framework).
