### ISSUE TITLE
cmd/ctrl-click doesn't open link in new tab

### ISSUE THREAD

**Issue by mattiasmak** [PuppetJs/PuppetJs#53]
When cmd/ctrl-click a link chrome (and other browsers I guess) opens the link in new tab. This doesn't work with puppetjs.

**Comment by warpech** [comment]
Confirmed. Good catch!

**Comment by warpech** [comment]
@miyconst could you take a look? This should be fixed in `puppet-dom.js`.

**Comment by miyconst** [comment]
Okay, I disabled morphing for ctrl + click and middle mouse button.

**Comment by warpech** [comment]
Please also check for `event.metaKey`, which represents the cmd key on Mac

**Comment by miyconst** [comment]
Sorry, completely forgot about Mac users. Done.
