### ISSUE TITLE
Multiple <puppet-client> elements => Uncaught Error: Session lost...

### ISSUE THREAD

**Issue by andwah** [PuppetJs/PuppetJs#55]
The order how you create ```puppet-client``` is the difference below

This will work;
```
<puppet-client ref="root"></puppet-client><!-- plug in client-server sync -->
<puppet-client remoteUrl="http://localhost:8181/api/servermodel" ref="myModel"></puppet-client>
```

This will **NOT** work:
```
<puppet-client remoteUrl="http://localhost:8181/api/servermodel" ref="myModel"></puppet-client>
<puppet-client ref="root"></puppet-client><!-- plug in client-server sync -->
```
Console output:
```
Uncaught Error: Session lost. Server replied with a different session ID that was already set. 
Possibly a server restart happened while you were working. 
Please reload the page.

Previous session ID: /__default/E0F17FA7F6BFD9C320000010
New session ID: /api/servermodel/8afb19cd-23a1-4b0f-ae84-ad5384886511/B1D8149B6011F0B1A0000010```

**Comment by tomalec** [comment]
I guess it may be related to the fact that we receive referrer in Cookie, and the name is same for both instances.

**Comment by warpech** [comment]
Maybe we should ignore cookie if remoteUrl is provided in the config?

**Comment by miyconst** [comment]
Ping @tomalec & @warpech. Is this issue important?

**Comment by warpech** [comment]
Yes.

The only solutions I can think of are:

1. PuppetJs should not remove `Location` cookie, so that other instances can read it
2. PuppetJs should copy the value of `Location` cookie to a global variable and then delete the cookie. Other instances of PuppetJs can read the value from the global variable

I think solution 2 is better

**Comment by tomalec** [comment]
@warpech, I think that both solutions you proposed will not work when you connect to two different removes, as Location cookie form one will overwrite `remoteURL` of another.

**Comment by warpech** [comment]
True. Ideas?

**Comment by tomalec** [comment]
Maybe we should limit & simplify usage of cookies in Puppet communication, and:
1. Read cookie on init, to set default `remoteURL` if nto provided, then
2. Read only `X-Location` response header to change `remoteURL` in runtime, as the response will be read by sender - applicable instance.

However, I'm not sure how it will work with morphed pages, and WebSocket connections (but those were not covered anyways, were they?)

**Comment by warpech** [comment]
> Maybe we should limit & simplify usage of cookies in Puppet communication, and:
1. Read cookie on init, to set default `remoteURL` if nto provided, then
2. Read only `X-Location` response header to change `remoteURL` in runtime, as the response will be read by sender - applicable instance.

So the only change from current code is that cookie should be only read on init, and only if `remoteUrl` is not provided. Do you confirm?

If yes then I agree. Additionally, cookie handling should be moved from `puppet.js` to `puppet-dom.js`.

> However, I'm not sure how it will work with morphed pages, and WebSocket connections (but those were not covered anyways, were they?)

This is a separate problem, also mentioned in https://github.com/PuppetJs/PuppetJs/issues/67#issuecomment-115299616

**Comment by tomalec** [comment]
> So the only change from current code is that cookie should be only read on init, and only if `remoteUrl` is not provided. Do you confirm?
I do :)
> Additionally, cookie handling should be moved from puppet.js to puppet-dom.js.
:+1:

**Comment by warpech** [comment]
Cool! @miyconst could you do the change, on a separate branch?

**Comment by miyconst** [comment]
The new branch: https://github.com/PuppetJs/PuppetJs/tree/issues/55---Multiple-puppet-client.

`<puppet-client>` also got some changes, - https://github.com/PuppetJs/puppet-client/tree/issues/55---Multiple-puppet-client.

**Comment by miyconst** [comment]
@warpech, @tomalec, could some of you review the changes and give me the green light to merge?

**Comment by warpech** [comment]
Looking at the code, this is totally how I imagined it.

@tomalec please do a final review. When done, please reassign it back on @miyconst for merging.

After this is released, all code samples given in first message of this thread should work the same way.

**Comment by miyconst** [comment]
Merged.

**Comment by tomalec** [comment]
Here is the only comment I have https://github.com/PuppetJs/PuppetJs/commit/0ab51521461ff547444dafe5aa929918f7f08456#commitcomment-11911586

**Comment by miyconst** [comment]
Accepted the comment.

**Comment by tomalec** [comment]
Cool :) Could you also provide a automated test for multiple instances somehow? or would it be too much work mocking the servers?

**Comment by miyconst** [comment]
Created a separate issue for the test. Closing this one.
