### ISSUE TITLE
Links in the demo don't work correctly

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#56]
Links in the demo don't work correctly.

Steps to reproduce: 

1. Go to: http://puppetjs.github.io/PuppetJs/lab/polymer/index.html
2. Click on "ShadowDOM: Nikola Tesla"
3. Observe that the data in the form does change
4. Click on "Albert Einstein"
5. Observe that the data in the form does not change, which is an error

Tested in Chrome 43, Firefox 38

**Comment by miyconst** [comment]
Fixed. The issue was with session. The mockServer returned new session for each request, and puppetjs throws `Session lost.` exception if the new session is not equal to the previous one.

Replaced session with `"/PuppetJs/lab/polymer/index.html"` instead of `this.url`.

**Comment by miyconst** [comment]
Tested in Chrome and Firefox.

**Comment by warpech** [comment]
Still something wrong:

1. Go to http://puppetjs.github.io/PuppetJs/lab/polymer/index.html
2. Click on ShadowDOM: Nikola Tesla link
3. In the form on the right, the text changes to `Nikola`, `Tesla`
4. Change `Nikola` to `Nikolas`
5. Error: The header says `Nikolas` but the input says `Albert`

![bug](https://cloud.githubusercontent.com/assets/566463/8201818/bb81f070-14d4-11e5-92ef-fd72c200fd16.gif)

**Comment by miyconst** [comment]
It looks like this issue is not related to my changes as was there long time ago. Fixed one more time.

**Comment by warpech** [comment]
Thanks!

1) It is not clear why this works when I use http://puppetjs.github.io/PuppetJs/lab/polymer/subpage.html as the starting URL, since now the `Location` is hardcoded in the mock server to `/PuppetJs/lab/polymer/index.html`

2) How will this work if I clone the demo locally and run it from `http://localhost/PuppetJs_env/PuppetJs/lab/polymer/index.html`?

**Comment by miyconst** [comment]
1) This is done inside `handlePageLoad` function, which checks current `url` and sets corresponded values to model.

2) All you have to do is install bower dependencies. I tested both demos (polymer & polymer_ot) locally.

**Comment by warpech** [comment]
I think I know what is happening there now. 

Server sets the values at `stub.responseHeaders = [{name: "Location", value: "/PuppetJs/lab/polymer/index.html"},{name: "X-Referer", value: "/PuppetJs/lab/polymer/index.html"}];` but actually never cares about them (in contrary to Starcounter implementation, which actually cares). The client also doesn't care, but it checks if they are the same.

The whole demo works if that line is removed. Can remove it and test it?

**Comment by miyconst** [comment]
You are completely right. I thought those headers are presenting "server behaviour". Now they are removed and the demo works like a charm.

**Comment by warpech** [comment]
Great!
