### ISSUE TITLE
OT demo does not work

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#57]
There are few errors in the OT demo (http://puppetjs.github.io/PuppetJs/lab/polymer_ot/index.html). Seems to be the fault of outdated Jasmine URLs.

**Comment by miyconst** [comment]
Fixed jasmine urls, replaced session with `"/PuppetJs/lab/polymer/index.html"`, added `PuppetDOM` to capture link clicks.

What is the visual difference between these two demos:
http://puppetjs.github.io/PuppetJs/lab/polymer_ot/index.html
and
http://puppetjs.github.io/PuppetJs/lab/polymer/index.html

They look identical.

**Comment by warpech** [comment]
OT is not visual, but it adds version numbering to Puppet messages, as described: https://github.com/PuppetJs/PuppetJs/wiki/Server-communication:-advanced-synchronization

I am not sure it deserves a separate demo, though. It is more of a playground to check if it works

**Comment by miyconst** [comment]
Okay, then I close the issue as demo works now.
