### ISSUE TITLE
WebSocket disconnection message should be displayed as error

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#62]
WebSocket disconnection message (https://github.com/Starcounter/Starcounter/issues/2332), which is used by Starcounter to send server side exceptions to the client, should be displayed as an error in the web browser console.

**Comment by miyconst** [comment]
@warpech it already works like this, it is shown on the console, but not on the page.

![ws-close-reason-1](https://cloud.githubusercontent.com/assets/6435556/8155569/290537b6-134e-11e5-96e5-ce00df62d86b.png)

![ws-close-reason-0](https://cloud.githubusercontent.com/assets/6435556/8155570/2c68332c-134e-11e5-9098-1e024aa0442f.png)

**Comment by miyconst** [comment]
@warpech I close this issue as it already works like you described.

**Comment by warpech** [comment]
Does it work with exception stack traces? My testing code was:

```c#
    void Handle(Input.Cancel action) {
        throw new Exception("Bad server!");
    }
```

**Comment by miyconst** [comment]
As I pointed in this comment: https://github.com/Starcounter/Starcounter/issues/2332#issuecomment-111400971 this does not work at all. 

@alemoi said that we have to explicitly set ws disconnection message, then it will be send to the client.

**Comment by alemoi** [comment]
Throwing an exception does not disconnect the websocket. Disconnect should be called explicitly with a message.

**Comment by warpech** [comment]
I reopened https://github.com/Starcounter/Starcounter/issues/2332
