### ISSUE TITLE
Add new validation rule: VALUE_OBJECT_CANNOT_CONTAIN_UNDEFINED

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/PuppetJs#64]
By @warpech in https://github.com/PuppetJs/PuppetJs/issues/21

Fair enough!  PuppetJs in debug mode (currently ON by default) validates outgoing patches:

```js
   if(this.debug) {
      this.validateSequence(this.remoteObj, patches);
    }
```

in which case the error should be reported. I am glad that we both agree :)

> @miyconst: Current validation is implemented here: https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch-duplex.js#L632

> And it is throwing OPERATION_VALUE_REQUIRED for undefined values, which should be replaced with VALUE_OBJECT_CANNOT_CONTAIN_UNDEFINED.

It should not be mixed. The current check for `undefined` value (`OPERATION_VALUE_REQUIRED`) should be kept. A new check for `undefined` property of the value (if the value is an object) should be added after it (`VALUE_OBJECT_CANNOT_CONTAIN_UNDEFINED`).

@miyconst could you prepare a solution for this on a separate branch in https://github.com/Starcounter-Jack/JSON-Patch? Create a new issue for it, publish code on a separate branch for review. The changes should include test and update to README.md

**Comment by miyconst** [comment]
@warpech I don't access to that repository.

**Comment by warpech** [comment]
Unfortunately I cannot give you access there... I will ask @Starcounter-Jack. In the meantime, could you do it as a pull request?

**Comment by warpech** [comment]
You should have access now

**Comment by warpech** [comment]
Please recreate this issue in JSON-Patch issues board
