### ISSUE TITLE
PuppetJs and Polymer 1.x

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/PuppetJs#65]
Polymer 1.x does not automatically track changes in bound js object. `this.set` and `this.notifyPath` methods should be used to notify Polymer that a property of an object was changed.
https://www.chromium.org/developers/polymer-1-0

After each server change in `puppet.obj` I have to explicitly notify Polymer that there were changes:
```js
puppet.addEventListener("patchreceived", function (e) {
    //Setting timeout to don't notify Polymer before puppet applies changes.
    setTimeout(function () {
        var patches = JSON.parse(e.detail.data);

        for (var i = 0; i < patches.length; i++) {
            var path = patches[i].path;

            //Skip version patches.
            if (/^[/]_ver/gi.test(path)) {
                continue;
            }

            that.notifyPath("model" + path.replace(/[/]/gi, "."), patches[i].value);
        }
    });
});
```

The `puppet.patchreceived` occurs after patch received, but not yet applied, that is why a timeout needed before notifying Polymer. It would be better to add `puppet.patchapplied` event to don't use timeout.

`puppet-client` is almost a pure web components, except one line of code:
```js
element.bindingDelegate = new PolymerExpressions(); // Make the "item" bindings work
```

If we could remove this line, then we could use same version of `puppet-client` with Polymer 0.5 and Polymer 1.x. In my demo I commented out the line.

I have to add `bower_components` subfolder for the demo and copy all of the dependencies to there including PuppetJs itself, because Polymer 0.5 and 1.0 can't be installed in the same folder.

So my suggestions are:

1. Add `puppet.patchapplied` event.
2. Somehow eliminate PolymerExpressions from `puppet-client`. For example fire an event instead of setting `bindingDelegate` and the Polymer 0.5 users would subscribe for the event and set the `bindingDelegate` value.
3. Move Polymer 1.x demo to other project/repository/solution to be able to use common webcomponents folder. I don't know how this could be possible before we migrate all of the components to Polymer 1.x.

The demo is not pushed yet. I can push it as is (it does not break anything) or may create another branch for it.

**Comment by warpech** [comment]
Good investigation! Please push it to a new branch, so we can have a look.

**Comment by miyconst** [comment]
Done. Here the new branch: https://github.com/PuppetJs/PuppetJs/tree/issues/65

The demo is inside /lab/Polymer_1 folder. All of the bower dependencies are commited.

**Comment by warpech** [comment]
@tomalec can you review it so we can discuss it tomorrow?

**Comment by warpech** [comment]
From my perspective it looks like we are on a right track but still a lot of work before us. It is great that it works at all!

Defining a custom element (`index-root`) is a good start, but it removes the declarative usage of templates that we have now with Polymer 0.5. 

The desired way to use it:

```html
   <template is="puppet-dom-bind" id="root">
        <h1>{{text}}</h1>
        <p>{{message}}</p>
        <p>
            <template is="dom-repeat" items="{{pages}}">
                <template is="dom-if" if="{{selected}}">
                    <span>{{name}}</span>
                </template>
                <template is="dom-if" if="{{!selected}}">
                    <a href="{{name}}">{{name}}</a>
                </template>
            </template>
        </p>
        <div>
            <button type="button" on-click="{{click$++}}">
            <!-- 
             or a filter or a decorator... at least: <button type="button" onclick="this.templateInstance.model.click$++}}">
             compare to nice discussion in: https://github.com/PuppetJs/PuppetJs/issues/31 
            -->
                <span>Click me (<span>{{click$}}</span>)!</span>
            </button>
        </div>
    </template>
    <puppet-client ref="root" usewebsocket="false"></puppet-client>
    <script>
    window.addEventListener("WebComponentsReady", function () {
        var root = document.getElementById("root");
        var puppet = document.querySelector("puppet-client");
        root.puppet = puppet;
    });
    </script>
```

@miyconst, @tomalec - WDYT?

**Comment by miyconst** [comment]
Yes, this looks better. I will try to make it work in this way.

**Comment by tomalec** [comment]
Why do we need stuff in `window.addEventListener`, I thought puppet-client can do that

I'd also suggest to add another way to use it - a way to avoid `ref` and `id`:
```html
<puppet-client usewebsocket="false">
    <template is="puppet-dom-bind">
        ...
```

**Comment by tomalec** [comment]
Speaking of `patchereceived`/`patchapplied` events, I'm a bit afraid of `path.replace(/[/]/gi, ".")`
at [index-root.html#L66](https://github.com/PuppetJs/PuppetJs/blob/issues/65/lab/polymer_1/index-root.html#L66) and other regular expressions like `/^[/]_ver/gi.test(path)`, as we would need to make sure to handle all (escaped) special chars, plus regular expressions may be expensive.

Maybe we could somehow use Polymer internal features - https://github.com/Polymer/polymer/tree/master/src/lib in our `template is="puppet-dom-bind"`?

**Comment by miyconst** [comment]
I tried not to change `puppet`, `puppet-client` and other existing libraries. Should I change those libraries in the branch?

The changes @tomalec propose would also be welcome for `Polymer 0.5`, that is why I would like to keep puppet *improvements* and *migration* to `Polymer 1.0` as separate tasks, and don't mix it up.

**Comment by tomalec** [comment]
:+1:

**Comment by warpech** [comment]
> I'd also suggest to add another way to use it - a way to avoid `ref` and `id`:
```html
<puppet-client usewebsocket="false">
    <template is="puppet-dom-bind">
        ...
```

This feature proposal is already tracked in other issues: 
https://github.com/PuppetJs/PuppetJs/issues/67#issuecomment-115299616
https://github.com/PuppetJs/PuppetJs/issues/63#issuecomment-115304598

I agree to keep the current issue to Polymer 1.0. upgrade only, without adding new features.

**Comment by miyconst** [comment]
I have reworked `index-root` to be `<template is="puppet-dom-bind">`. There are some problems:

1. Polymer 1.0 does not yet support inheritance, that is why I copied code from `<template is="dom-bind">`.
2. I could not find a way to obtain model by html element in Polymer 1.0, that is why I used js function to handle click instead of inline handlers.

**Comment by warpech** [comment]
1. How about not copying code from `<template is="dom-bind">` but importing `dom-bind` it and wrapping it inside `puppet-dom-bind`?
2. I also couldn't find a way to do it, but there must be. @tomalec can you help?

**Comment by miyconst** [comment]
1. This is not possible. We cannot use `<template is="dom-bind">` inside any Polymer element.

This does not work either:
```html
<dom-module id="puppet-dom-bind">
    <template>
        <content></content>
    </template>
    <script>
    </script>
</dom-module>
```

```html
<puppet-dom-bind id="puppet-root">
    <h1>{{model.text}}</h1>
</puppet-dom-bind>
```

In this case `{{model.text}}` being bound to model of `puppet-dom-bind` not the one inside it.

**Comment by miyconst** [comment]
I tried to implement `imported-template` with polymer 1.0, and was able to achieve similar functionality with lots of hack. The new element name is `puppet-import`. In spite of 

>Auto-binding templates should only be used outside of a Polymer element.
https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-bind

I still used `dom-bind` to stamp loaded html on the page. 

The data model is the problem again. The template should be explicitly notified about each change in the model.

For this purpose I modified `puppet-dom-bind`:

```js
notifyAll: function (path, value) {
    var imports = document.querySelectorAll("puppet-import");

    this.notifyPath(path, value);

    for (var i = 0; i < imports.length; i++) {
        imports[i].template.notifyPath(path, value);
    }
}
```

This functions notifies every `puppet-import` on the page about a change in the model. The problems are:

1. A `puppet-import` might be bound to a part of `puppet.obj` then it's path won't be the same as `puppet-dom-bind` path.
2. A `puppet-import` might be bought to another `puppet`, but will be notified about each change of all puppets.

**Comment by miyconst** [comment]
I have added `path` attribute to `puppet-include` element to solve problem 1 from the previous comment.

**Comment by miyconst** [comment]
With those elements/hacks/changes I was able to make a somehow working Launcher + App using Polymer 1.0, can push source code to GitHub if needed.

**Comment by miyconst** [comment]
Another problem discovered.

For Polymer 1.0 changes at path `/model/array/4` does not mean that the `/model/array` was aslo changed. This leads to bugs with `dom-repeat`.

```html
<template is="dom-repeat" as="item" items="{{model.array}}">
    <div>{{item.Name}}</div>
</template>
```

Assuming that the `array` has three items. A patch comes from the server:

```js
{
    op: "add",
    path: "/model/array/4",
    value: { Name: "Test row" }
}
```

Even though I notify about each change with `this.notifyPath(path, value)` the `dom-repeat` won't be re-bound, because the `/model/array` was not changed from the Polymer's point of view.

**Comment by miyconst** [comment]
I have added an ugly workaround for the previous issue, which calls `this.notifyPath("model.array", this.array.slice())`, was not able to find any better way.

**Comment by warpech** [comment]
In case we need to do without Polymer's data binding at all, here's some interesting alternatives (no particular order):

- http://rivetsjs.com/
- https://github.com/remy/bind.js
- http://www.ractivejs.org/
- http://gwendall.github.io/way/
- https://github.com/grnadav/databind
- http://vuejs.org/guide/
- https://muut.com/riotjs/

They all support two-way data binding including form elements, but some require extensive configuration. I didn't evaluate much.

Conceptually PuppetJS should support any of these.

**Comment by tomalec** [comment]
> Conceptually PuppetJS should support any of these.

Yes, as PuppetJs itself works fine with any Polymer versions, the thing we still struggle, is "how will we use Polymer 1.x template engine to render view model from JSON"

**Comment by tomalec** [comment]
BTW, for migration of our use cases we could try http://polymerlabs.github.io/polyup/
