### ISSUE TITLE
puppet-dom does not catch link clicks inside web componenets

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/PuppetJs#66]
In André's application puppet-dom does not catch link clicks inside his own Polymer component.

I try to reproduce the issue, and will ask André for the source code if no success.

**Comment by miyconst** [comment]
@warpech, `puppet-dom` has a public function `PuppetDOM.prototype.findShadowRoots` which is not used any more. Does anyone use it outside of `puppet-dom`, can I remote it?

**Comment by warpech** [comment]
It was supposed to be for internal use only. You can remove it.

**Comment by miyconst** [comment]
Removed. Now `puppet-dom` is about twice less in size.

**Comment by tomalec** [comment]
:clap: Fixing, and adding features by removing the code - That's what we call "Extreme Clean Solution" :trophy: ;)

I've released it as a new version [1.2.0](https://github.com/PuppetJs/PuppetJs/releases/tag/1.2.0), do you think that's worth mentioning in release notes?

**Comment by miyconst** [comment]
It does not add any major features, just a bug fixing and code refactoring, not that important for a special mention. Of course, if you would like to mention it, I have nothing against.

**Comment by warpech** [comment]
I think every bug fix needs to be mentioned in release notes - that's what release notes are for
