### ISSUE TITLE
Change onPatchReceived, onRemoteChange, etc callbacks to Events

### ISSUE THREAD

**Issue by tomalec** [PuppetJs/PuppetJs#74]
PuppetJs already implements EventTarget API, so why shouldn't we use it for 
 - `onPatchSent`
 - `onPatchReceived`
 - `onRemoteChange`
 - `onSend`
 - `onReceive`
 - `onError`
 - `onStateChange`
 - `onSocketStateChanged`
AFAIK those are used only to expose events to `<starcounter-debug-aid>` and to `<puppet-client>` - which then translates those callback to DOM events anyways.
So we use them to communicate stuff between HTML Elements, and DOM way to comunicate between elements is Events :)

Thanks to the fact that puppet-client `call`s `Puppet` constructor on `this`, we could also remove glue coda on translating callback to events.

@warpech, @miyconst WDYT?

**Comment by tomalec** [comment]
BTW, should we then change names to `"socket-state-changed"`?

**Comment by warpech** [comment]
Good idea! Note that standard W3C event names are lower case, single word: https://developer.mozilla.org/en-US/docs/Web/Events

**Comment by warpech** [comment]
cc @joozek78

There should be a transition period in which callbacks are working but result in a warning.

**Comment by warpech** [comment]
@tomalec last time we discussed, we have proposed to do the other way round - replace the events with callbacks, which I think is a good long term goal, but does not have to be done immediately. 

This is also in line with what you wrote here: https://github.com/PuppetJs/PuppetJs/pull/90#issuecomment-233409023

Should we close this?

**Comment by tomalec** [comment]
agree
