### ISSUE TITLE
Add bump method

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/PuppetJs#75]
There should be a `bump` method which would increase client version and send an empty update to server.

**Comment by miyconst** [comment]
@tomalec I think it's no longer needed. Closing the issue.

**Comment by tomalec** [comment]
Cool, thanks. Don't we need that for bumping the session? (in cleaner way)

Is it related to https://github.com/PuppetJs/PuppetJs/issues/29#issuecomment-170922689 ?

**Comment by miyconst** [comment]
We thought that we might use it somewhere else apart of `puppet-client` which ping server to keep session alive.

Till now nobody uses it, and puppet-client can use it's internals to do something. Don't think we need a separate method for it. At least for now.
