### ISSUE TITLE
Problems with Patches 

### ISSUE THREAD

**Issue by mattiasmak** [PuppetJs/PuppetJs#76]
Consider the following example.

this.set('itemdropped.Somedata$', 1);
this.set('itemdropped.Someotherdata$', 2);
this.set('itemdropped.Evenmoredata$', 3);

// Trigger the patch.
this.set('itemdropped.Trigger$', this.itemdropped.Trigger$+1); 

The patch does not put the the values is natural order and all values is not set when reaching the handler. I guess there's logical explainations due to async/event mechanisms. But what's the best practice? It should be solved I think.

Icould make just one big string that is set with data and triggers the patch and then parse it on server. But that feels like a huge hack.

this.set('itemdroppen.Alldata$', '1,2,3');

**Comment by warpech** [comment]
Related: https://github.com/PuppetJs/PuppetJs/issues/29

**Comment by miyconst** [comment]
Not sure this is the best practice, but I used `setTimeout` in such cases. So, the order depended values were sent in different patches.

This might now work in the last version of `fast-json-patch` as `Object.observe` is no longer supported.

**Comment by warpech** [comment]
@mattiasmak thanks for reporting. We will be solving this. The proposal of changes is tracked in #29. Please follow that issue.

In the meantime, please use some of the described workarounds.
