### ISSUE TITLE
Deprecation proposal: Remove $parent

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#79]
PuppetJs supports special notation: a `$parent` alias. For example, the following notation:

```
puppet.obj.deep.$parent.name
```

Is equivalent to:

```
puppet.obj.name
```

As of now, it does not work with Polymer 1.2 and 1.3, because Polymer creates an explicit binding to a path `model.deep.$parent.name` and ignores changes that are set on `model.name`.

It can be fixed by normalizing Polymer bindings:

```javascript
            var templates = document.querySelectorAll("template");
            for(var i=0; i<templates.length; i++) {
                if(templates[i]._propertyEffects) {
                    for(var key in templates[i]._propertyEffects) {
                        if(templates[i]._propertyEffects.hasOwnProperty(key)) {
                            for(var j=0; j<templates[i]._propertyEffects[key].length; j++) {
                                if(templates[i]._propertyEffects[key][j].effect) {
                                    if(typeof templates[i]._propertyEffects[key][j].effect.value == "string") {
                                        if(templates[i]._propertyEffects[key][j].effect.value.indexOf(".$parent.") > -1) {
                                            templates[i]._propertyEffects[key][j].effect.value = collapseParent(templates[i]._propertyEffects[key][j].effect.value);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

    function collapseParent(str) {
        var parts = str.split(".");
        var n = parts.length - 1;
        while (n >= 0) {
            if (parts[n] == "$parent") {
                parts.splice(n-1, 2);
                n--;
            }
            n--;
        }
        return parts.join(".");
    }
```

But even better solution is to avoid this problem but stopping the support for `$parent` in PuppetJs. I propose to do this after Starcounter 2.2 is released.

**Comment by tomalec** [comment]
LGTM,
I don't think we have any real use-case for `$parent`. On the other side it cost us a lot (performance, maintenance), requires more documentation, and for sure provides more magic, to otherwise pure JSON object.

**Comment by warpech** [comment]
Some `$parent` is used in Administrator: https://github.com/Starcounter/Starcounter/blob/57c6d056c5a43e4ffabbea3f261e3f30219220b1/src/Starcounter.Administrator/app/partials/databaseNew.html

But I think it's Angular's, not Puppet's.

**Comment by warpech** [comment]
@joozek78 please do it if you find it convenient for your current work.

You can remove `markObjPropertyByPath`, `recursiveMarkObjProperties`, `placeMarker`.

**Comment by malx122** [comment]
This would have been a REALLY good thing to know of. (Searching tunity code for "$parent" -> 74 hits)...

**Comment by warpech** [comment]
Sorry! How could we improve? I guess the information could be added to https://github.com/PuppetJs/PuppetJs/releases

**Comment by malx122** [comment]
Since it is a breaking change, yes that would have been good.

**Comment by warpech** [comment]
@joozek78 can you pls add it?

**Comment by joozek78** [comment]
I've added it at https://github.com/PuppetJs/PuppetJs/releases/tag/2.2.0

**Comment by tomalec** [comment]
Maybe we should also add short not in the changelog of SC?

**Comment by warpech** [comment]
I think that would be too much. A link to a range of PuppetJs release notes would be perfect.

**Comment by joozek78** [comment]
Something like this?
> Updated PuppetJs from 2.0.0 to 2.2.0 (https://github.com/PuppetJs/PuppetJs/releases)

I just don't know how deep should we go with this dependency report. Currently there are following templates in changelog (presented with old version number):

> - Upgraded starcounter-debug-aid from 2.0.5 to 2.0.7
> - Upgraded Juicy/juicy-jsoneditor from 1.0.5 to 1.1.0
> - Upgraded Josdejong/jsoneditor to 5.5.6
> - Upgraded Juicy/imported-template from 1.4.0 to 1.4.3
> - Upgraded puppetjs/puppetjs from 1.3.8 to 2.2.1
> - Upgraded puppetjs/puppet-polymer-client from 2.0.0 to 3.2.0

What is the key to determining which dependencies are important enough to report here? I feel that it would be enough to have puppet-client, puppetjs, and polymer here. Or else everything we updated

**Comment by warpech** [comment]
I think all are relevant, because otherwise they would not be upgraded.

> Updated PuppetJs from 2.0.0 to 2.2.0 (https://github.com/PuppetJs/PuppetJs/releases)

This looks nice to me. Can you please change that in CHANGELOG.md?

**Comment by joozek78** [comment]
Here you go: https://github.com/Starcounter/Starcounter/commit/b871a333d2abac087cce81f487afc805db5a0a29

**Comment by warpech** [comment]
Thanks!
