### ISSUE TITLE
Reflection on Server Communication wiki

### ISSUE THREAD

**Issue by per-samuelsson** [PuppetJs/PuppetJs#80]
@tomalec 

Nice read over at https://github.com/PuppetJs/PuppetJs/wiki/Server-communication.

How up-to-date is that, just generally?

Also, can you just hint to me in a few lines just a little more detailed on how this is achieved:

> While the page is being loaded, PuppetJs will ask the server for the JSON data pertaining to the web page (a.k.a. the page data or view model). By default, PuppetJs will use the same URL as for the web page itself, but instead of asking for HTML (i.e. Accept header set to text/html) it will ask for JSON (Accept header set to application/json). This request is made automatically.

Basically, I think what I'm curious about is what trigger it to do that? Is it triggered by some content in the page (which seem unlikely, since you say its doing this while the page loads), or is it simply triggered because the page somehow reference PuppetJs, .e.g. using an import or script or however it is done to "include things" in the mystic client world of you web wizard guys. :smile: 

Thanks.

**Comment by tomalec** [comment]
Thanks, however most of the work was dome by @warpech 

It's _almost_ up to date ;)

The bigest change I found is, the fact that initial HTML should look like:
#### Custom Element way:
```html
HTTP/1.1 200 OK
Content-Type: text/html
Location: /emails

<!doctype html>
<head>
   <!-- load web components polyfill if needed -->
   <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
   <!-- load puppet-client -->
   <link rel="import" href="bower_components/puppet-client/puppet-client.html">
</head>
<puppet-client></puppet-client>
<ul>
</ul>
```
Then once `puppet-client` is attached to the document it established the Puppet connection

#### Pure JS way
```html
HTTP/1.1 200 OK
Content-Type: text/html
Location: /emails

<!doctype html>
<head>
   <!-- load PuppetJS library -->
   <script src="bower_components/puppetjs/puppet.js"></script>
</head>
<script>
 var puppet = new Puppet();
</script>
<ul>
</ul>
```
once `puppet` instance is created it established the Puppet connection

---

Is that more-or-less what you need or would you like be to elaborate more on how establish process goes?

@warpech Should we somehow sync Puppet wiki with gitbook? or maybe we can create gitbook for puppet protocol/flow only?

**Comment by tomalec** [comment]
@per-samuelsson If you would like to use Puppet with Polymer template binding you may prefer Polymer specific `puppet-client` -https://github.com/PuppetJs/puppet-polymer-client

Then you may use it as simple as:
```html
<template is="dom-bind">
   <puppet-polymer-client obj="{{model}}"></puppet-polymer-client>
   <h1>Hello <span>{{model.name}}</span></h1>
</template>
```

**Comment by per-samuelsson** [comment]
Thanks @tomalec, that's kind of what I need I think, I was basically just after some more knowledge on how its approached, and that kind of cover it.

Just one final thing, about this:

> [...]  it established the Puppet connection

And part of that is shooting that request for JSON view model, right?

**Comment by warpech** [comment]
> And part of that is shooting that request for JSON view model, right?

Yes.

I have changed the example and text to be more clear: https://github.com/PuppetJs/PuppetJs/wiki/Server-communication/_compare/722e72c2268bd194f7f36aa22e00d3ea2d8e77c5...d54c86fd5b0cf0703e792cf4f2d7ec8be1ff9251

Please ask more questions when you feel like it. Thanks!
