### ISSUE TITLE
onRemoteChange deprecated? (onLocalChange proposal)

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#81]
Since this commit (https://github.com/PuppetJs/PuppetJs/commit/126455697921be73b31809fc959246bf3132d50e), `onRemoteChange` is marked in README.md as "Deprecated".

Did we discuss it?

I would like to add a new callback `onLocalChange`, which is useful for `puppet-polymer-client`. But then I need to "undeprecate" `onRemoteChange`.

`onPatchSent` is almost suitable for me, but I dislike the fact that `data` is a string there.

**Comment by warpech** [comment]
cc @miyconst, @tomalec 

The question is - do you agree to add `onLocalChange` and undeprecate `onRemoteChange`?

Alternatively, I would like to change the argument of `onPatchSent` and `onPatchReceived` to be the actual array (sequence of patches). Right now it is string.

**Comment by miyconst** [comment]
>The question is - do you agree to add `onLocalChange` and undeprecate `onRemoteChange`?

If we need `onLocalChange` then it is very likely someone would also need `onRemoteChange`. So, I would either keep both or remove both.

>Alternatively, I would like to change the argument of `onPatchSent` and `onPatchReceived` to be the actual array (sequence of patches). Right now it is string.

I also thought so, and at some point was going to change it. Those events rise even if the patch received from the server is not a valid json, and this helps debugging. What if we extend the argument, not replace it?

**Comment by tomalec** [comment]
Please note, the fact that patch was received does not mean it was applied, due to JSON-Patch-Queue.

I also like the idea to exposing data in already parsed format, but to avoid performance overhead of JSON parsing just for debugging/external use, I would prefer to parse it once for the queue and call back then.

Regarding renaming, I would like to rename `callback` argument to something more descriptive, like `onDataReady`

**Comment by warpech** [comment]
> Please note, the fact that patch was received does not mean it was applied, due to JSON-Patch-Queue.

Because of that, I think that I actually **need** `onLocalChange` and `onRemoteChange` - because my external JavaScript (in this case `puppet-polymer-client`) works on the local object.

**Comment by miyconst** [comment]
Let's add `onLocalChange` and de-deprecate `onRemoteChange` then?

**Comment by tomalec** [comment]
I think we are all agreed, aren't we?

**Comment by warpech** [comment]
Yeah, thanks! Done
