### ISSUE TITLE
New name for PuppetJs

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#83]
Whenever I speak to people working as devops, they ask me if PuppetJs is an interface to [Puppet](https://en.wikipedia.org/wiki/Puppet_%28software%29), a very popular configuration management tool.

Of course it is not related. We should change the name to be something with no overlap with a popular library.

Another reason is that I would like to drop the "Js" part from the name. PuppetJs actually allows for SPAs with zero lines of arbitrary JS. Since it allows you to drop JS from your app, the name should not contain JS either!

Any proposals? "Puppeteer" sounds more unique, but it as well is taken on npm.

We own an organisation called "remote". Maybe it can be used.

**Comment by miyconst** [comment]
PuppetJs is a completely fine name for me, as I am not familiar with the popular Ruby Puppet library. Anyway, I agree with all of the statement above, and ready to rename it to something else.

The name should at least somehow explain of what it is. I dislike names such as `bower`, for me it's like Chinese characters, you either know it or don't know and not able to read.

My poor fantasy came up with those names: `Patcher`, `JsonPatcher`, `RemotePatcher`, `SocketPatcher`, but I am fine with whatever name you choose as long as it is reasonable.

**Comment by tomalec** [comment]
Maybe let's first decide which part we would like to name. Probalby we need names for all/most, but narrowing and describing the case may help us

1. Entire organization,
2. The protocol/communication pattern
3. Library to keep JSON synced in p2p, c2s communication via JSON-Pacth and WS/HTTP

(better descriptions welcome as well)

:+1: for dropping -JS.

I like the "remote" - as we let you use remote JSON, as if it would be local one.
However, I'm afraid it could be to generic.


Maybe instead of JS we could use JSON, as we are bound tigthly to JSON communication: PuppetJSON, JSONPuppeteer, JSONPuppets.

**Comment by compwright** [comment]
Puppet.json?

**Comment by tomalec** [comment]
Thanks @compwright , you have just inspired me to make... ;)

# Github-reactions-driven-voting:

Proposals starts  with :bulb:.
Add "+1" reaction to the name you vote for, you can vote for many, if you really need.

**Comment by tomalec** [comment]
:bulb: PuppetJSON

**Comment by tomalec** [comment]
:bulb: JSONPuppeteer

**Comment by tomalec** [comment]
:bulb: JSONPuppets

**Comment by tomalec** [comment]
:bulb: Puppeteer

**Comment by tomalec** [comment]
:bulb: Remote

**Comment by tomalec** [comment]
:bulb: Patcher

**Comment by tomalec** [comment]
:bulb:  JsonPatcher

**Comment by tomalec** [comment]
:bulb: RemotePatcher

**Comment by tomalec** [comment]
:bulb: SocketPatcher

**Comment by tomalec** [comment]
💡 JSONMirror

**Comment by Mackiovello** [comment]
JSONMirror is seriously genius. It makes a ton of sense

**Comment by warpech** [comment]
I like this, but without the `JSON` part. In future, we might allow other serialization formats (Protobuf, Capnproto, etc).

Maybe StateMirror, DataMirror, TreeMirror?

**Comment by warpech** [comment]
**Palindrome**

> (noun) a word, phrase, or sequence that reads the same backward as forward, e.g., madam

Or a word that is a palindrome, e.g. `locol`

**Comment by alshakero** [comment]
I realllyyyyyyyy like **Palindrome**.

**Comment by warpech** [comment]
Or more unique: **Palindrom** (which is actually the Swedish *and* Polish spelling)

**Comment by alshakero** [comment]
Logo proposal 
![image](https://cloud.githubusercontent.com/assets/17054134/22641739/39d5184c-ec58-11e6-931b-506f3a91170a.png)

**Comment by miyconst** [comment]
>Logo proposal

Remove the extra piece of the line on the left bottom and it looks perfect.

**Comment by alshakero** [comment]
@miyconst ah, I hate it too, but it's a **P**. Let's see what others think.

**Comment by miyconst** [comment]
>but it's a **P**

I could guess so after some hard imagination, but if that is **P**, the extra line should be longer, and the main part smaller.

**Comment by Mackiovello** [comment]
> Logo proposal

It looks good! Wouldn't we want to have the color scheme closer to the Starcounter color scheme?

**Comment by ubbeK** [comment]
Please wait with logo:s and such since the voting has not ended / decision has not been made.

I would like to add 1 or 2 names.

**Comment by miyconst** [comment]
>... the color scheme closer to the Starcounter color scheme?

Not me. PuppetJs can be used with or without Starcounter, just another product.

**Comment by Mackiovello** [comment]
> PuppetJs can be used with or without Starcounter, just another product.

That's right. It's still a Starcounter product which means that it probably should be branded as such. The same way that, for example, Google products have similar branding:

![google_product_icons-01](https://cloud.githubusercontent.com/assets/19392292/22642305/7ca57b74-ec5a-11e6-90a1-c6b527640e48.jpg)

**Comment by miyconst** [comment]
How about 

![](https://angular.io/resources/images/logos/angular2/angular.png)

and 

![](https://www.polymer-project.org/images/logos/p-logo.png)

Google made, does not really look similar.

**Comment by alshakero** [comment]
@Mackiovello, well at least @tomalec, @warpech and I agreed to advertise it as a standalone product. It's more beneficial for Starcounter than sticking to our color pallets. 
Here is how it looks if anyone is curious 
![image](https://cloud.githubusercontent.com/assets/17054134/22642561/7ca2dd50-ec5b-11e6-84da-6e3b685a393e.png)

**Comment by tomalec** [comment]
Guys, for a logo discussion, we have https://github.com/PuppetJs/PuppetJs/issues/34
Speaking of color schemes. Google keeps consistent colors for Google brands (Google Docs, Google Maps), and different for other brands (Polymer, Angular, etc)

**Comment by alshakero** [comment]
@tomalec I forgot about that. Should I move my proposal?

**Comment by tomalec** [comment]
@alshakero Please do.

@ubbeK How much time do you need for your proposals? I think, it would be great to give some deadline for name elections, and finally finish this problem after all those years ;)

**Comment by ubbeK** [comment]
@tomalec: If I am not happy with any of my ideas in 1 hour, I will probably vote for `palindrom`

**Comment by ubbeK** [comment]
Here are my idea:s

### Mythical oriented
[Narcissus](https://en.wikipedia.org/wiki/Narcissus_(mythology))
[Graeae](https://en.wikipedia.org/wiki/Graeae)

### Physics oriented
[Covalent bond](https://en.wikipedia.org/wiki/Covalent_bond)

I don't personally like them better than `palindrom` but I would still like to add them so we did not choose the first non-computer-science-choice that came up.

**Comment by Joltrix** [comment]
@ubbeK Oh wow, those suggestions are amazing in a way! :O Like, I get the meaning and how it can be "applied" to PuppetJS.

(+ bonus points since its from greek mytology ! )

Although, they might be a bit far fetched? Because, I doubt the common user will see "Graeae" and go like "oh, this can be used for two way binding", same thing with Narcissus. Although that one may be a bit more common, and people might connect it to the mirror.

Then again, I guess from the users PoV, palindrom isn't something completely obvious either, until they've checked the definition of the library, and then they'll maybe connect the dots.

In either case, I liked those suggestions! :D

**Comment by warpech** [comment]
I like @ubbeK's proposals, but `Bond`, `Covalent` and `Narcissus` are taken on NPM. 

`Graeae` super unique, but is a tong twister :) The alternative name for them is `Phorcides`, but doesn't look too appealing.

**Comment by threezool** [comment]
Some names based on latin translations:
**Reputati** (counterpart)
**Cogitatio** (reflection)

**Comment by warpech** [comment]
From the provided suggestions, only **Palindrom** and **Narcissus** sound catchy to me.

Narcissus is a negative term, though, which I find problematic. I imagine myself promoting Narcissus on a conference with slight shame :) Any ideas how to turn this into a positive term?

**Comment by miyconst** [comment]
>Any ideas how to turn this into a positive term?

Just use **Palindrom** :)

**Comment by warpech** [comment]
Maybe some translations of the word "mirror": **Spegel**, **Spiegel**, **Lustro**

**Comment by alshakero** [comment]
@warpech I love Lustro! Free on NPM too!

**Comment by miyconst** [comment]
>@warpech I love Lustro! Free on NPM too!

Sounds like "lamp" in Russian. Mirror in Russian is **Zerkalo**.

**Comment by tomalec** [comment]
To me lustro/mirror is something that reflect only you, so there is not way you could communicate with the peer on the other side of the mirror. 
[Through the Looking Glass](https://youtu.be/anvGUW-vsLE?t=24s) - Well.. to the story fits us well, we do reflect for the both sides, we do fiddle with time (OT) and we open entire new wonderland ;)

**Comment by alshakero** [comment]
So do we reach a consensus here?

**Comment by warpech** [comment]
I think nothing has gained more enthusiasm than **Palindrom** . Everyone please give a final vote (with your thumbs up or down) by the end of the week.

**Comment by tomalec** [comment]
@warpech Shall we close the issue, and proceed with renaming?

**Comment by alshakero** [comment]
I agree. Not sure if you saw, [I did the renaming ](https://github.com/alshakero/Palindrom), just want us to decide the appropriate repo to set it as origin and push.

**Comment by tomalec** [comment]
I'd simple rename PuppetJs or to Palindorm, then we will have full history since the beginning of Puppet. Plus, I'd keep JSON-Patch-OT related stuff in separate repos, as it is now.

**Comment by warpech** [comment]
I agree with @tomalec. Let's close this issue and create a new issue "Rename to Palindrom"

**Comment by tomalec** [comment]
New issue at https://github.com/PuppetJs/PuppetJs/issues/118
