### ISSUE TITLE
Add event that notifies about finished round-trip

### ISSUE THREAD

**Issue by joozek78** [PuppetJs/PuppetJs#86]
**This issue is supposed to spark some discussion, to find best solution to problem outlined below**

Context
--
When implementing tests in selenium it is easy to slip in a race condition. Consider following code:
```c#
button.Click(); // this triggers code-behind
Assert.That(driver.Url, Is.EqualTo($"{baseURL}/Redirect/apple"));
```
This code can fail should puppet not deliver its messages (and therefore trigger URL change) before assertion is executed

Current workaround
--
Currently one can only wait for expected effects of puppet completing its work (like a change in URL or some text). This, however has drawbacks:

1. You have to know when to wait for puppet, and it's not always obvious - it's easy to forget about wait after blurring an element and thus introduce race condition
1. You can't distinguish between puppet not delivering message (code-behind's or sending code's fault) and client code acting upon it (receiving code's fault) - you only know that the final effect has not been achieved
1. Code is more convoluted - instead of wait and then assert you get a mix of two

Proposed solutions
--

1. Add an event to puppet that fires when round-trip to backend has been finished. Add a helper to C# test code to wait for this event. This way it will be easier and more clear to wait for puppet to finish its job
1. Create facade over selenium methods that will automatically wait for puppet (when needed). This will solve the problem of forgetting to wait for puppet and also remove some clutter from test code. This can be done incrementally, adding most used methods (Click, SendKeys for starters) over time

**Comment by joozek78** [comment]
CC @tomalec @warpech @miyconst @aloscha

**Comment by warpech** [comment]
I'd vote for solution 2.

It is tricky to do the solution 1 right, because in WebSocket, there is no such thing as a request and response. The incoming and outgoing patches go on separate channels.

Only when PuppetJs is configured to apply OT (property `ot` set to true, which is the default) it is possible to know the match between a response and a request. But still I am negative towards solution 1, because this might encourage a non-declarative programming style.

**Comment by tomalec** [comment]
I'm also negative towards 1.

In JSON Patch communication/collaboration there is not such concept as "round-trip".

It is completely valid to send a message and do not receive any response. In here both peers are equal, they just modify JSON document.
(briefly we should not think of client requesting server changes, here we have just JSON document shared between two - once again we need better project page/demo https://github.com/PuppetJs/JSON-Patch-OT/issues/3)

I'm not very experienced with Selenium, but I believe 2. is the way to go. If we have problems to control async/distributed flow in tests, we should add helpers and facades there.

However I do not like "automatically" part of it. our browser - server collaboration is asynchronous and distributed, and we shouldn't pretend it's not.

**Comment by tomalec** [comment]
BTW, OT is supposed to solve conflicting/race scenarios, and we should test those as well.

**Comment by joozek78** [comment]
After discussion with @warpech I agree we shouldn't wait for puppet "round-trip". However, we could in future leverage heartbeats to detect when all messages have been received. I don't think that there is value now in adding a facade - I'd rather document testing patterns in gitbook
