### ISSUE TITLE
Investigate pushing patches on bigger scale

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#87]
During yesterday's CodeNight KitchenSink Map stopped getting notified about map marker position changes made in other clients. 3 or 4 clients where playing with it simultaneusly.

At this time I don't know if this was because of:
- disconnection (seems the most unlikely)
- malfunction of OT on the client side
- malfunction of OT on the server side
- malfunction of `CalculatePatchAndPushOnWebSocket` on the server side

Needs investigation

**Comment by miyconst** [comment]
During the lag time my cell phone was still updating successfully. We have to try to reproduce the issue with the opened console.

**Comment by warpech** [comment]
Archiving. Please report problems that are revealed during stress testing as separate issues.
