### ISSUE TITLE
Fix tests and connect to travis

### ISSUE THREAD

**Issue by joozek78** [PuppetJs/PuppetJs#89]
Currently, 7 tests fail on master branch.

**Comment by tomalec** [comment]
As for 2.2.0, 9 tests are NOT failing

**Comment by tomalec** [comment]
Most of the tests are passing, CLI command works, the only part left is https://github.com/PuppetJs/PuppetJs/issues/103

**Comment by warpech** [comment]
And #105

Closing as partially done, partially split to new tasks
