### ISSUE TITLE
Ping behavior

### ISSUE THREAD

**Issue by tomalec** [PuppetJs/PuppetJs#94]
Bellow is a side idea of discussion on problems with heartbeats, keeping session alive, and overhead of refreshing bindings.

Personally, I find "PING" and HEAD condition confusing and sticking out from entire flow/Puppet-protocol. If I remember correctly, some time ago we talked about "touch" functionality/method in PuppetJS (https://github.com/PuppetJs/PuppetJs/issues/29) we can also add `ping` method that will send also **valid** JSON Patch, that could be easily identified as no message, will not change a thing, and will not trigger any diff calculations, but still would touch the server and session. For example:

(1.)
```
[]
```

+ It would work fine with any protocol: HTTP, WS, or even Pigeon post ;)
+ will not require any exclusions to JSON Patch parser
+ will not require any arbitrary keyword to be documented

This is the messages that works more like regular ping: send tiny message, which is not a request for any action, and just check the connection.

We can also send just one or two test operation objects, that will let both peers to acknowledge the state of the other.

(2.)
```
[
   {op: "test", path: "ServerVersion", value: 70}
]
```

(3.)
```
[
   {op: "test", path: "ServerVersion", value: 70},
   {op: "test", path: "BrowserVersion", value: 60}
]
```

They also meet the benefits mentioned above.

For heartbeats, I would use a message that really beats the rythm - counts so both peers could follow same tune:
(4.)
```
[
   {op: "test", path: "ServerVersion", value: 70},
   {op: "test", path: "BrowserVersion", value: 60},
   {op: "replace", path: "BrowserVersion", value: 61}
]
```

Such message is definitely requesting a change, so it should be no surprise that an action is taken on server, and it may produce a response.

@warpech, @chrhol, @joozek78, @miyconst, @dan31
Does it make sense to you?

Correct me if I'm wrong, but as I understood on server-side we have few actions to cover:
1. Check the connection, and bump the session,
2. Respond with diff with all the changes made since last sync,
3. Refresh everything, to reset the browser's state.
@chrhol, @joozek78 could you check that and describe the actions we need to cover?

---

Related issues:
https://github.com/PuppetJs/PuppetJs/issues/29
https://github.com/PuppetJs/PuppetJs/issues/92
https://github.com/PuppetJs/PuppetJs/issues/93

**Comment by tomalec** [comment]
*In the email conversation @joozek78 wrote:*
> Regarding Tomek's idea

I think that heartbeat is conceptually on a "transport layer", whereas patches are "application layer". As such, it should be dependent on underlying transport and independent of patches. Imagine a situation where heartbeats are introduced into very WS standard - then we would need to disable our heartbeats for WS, but not for XHR

**Comment by tomalec** [comment]
Regarding layers I'd say that our idea is to "collapse the stack" that's why I'd like to avoid introducing new layers and think of it as just single _communication layer_ - JSON Patch. Then application logic need to bother only about changing the JSON, Puppet listens to those changes and uses just JSON Patch to communicate with a remote over the network (HTTP, WS)

**Comment by miyconst** [comment]
@tomalec you idea seems to be good for me, the only question is the implementation.

Currently, all of the known apps call `CalculatePatchAndPushOnWebSocket` when it's needed to push something from the server. Means, I am absolutely fine to don't update client side view-model on heart-beat patches.

**Comment by joozek78** [comment]
Heartbeats are needed only because of technical limitations of underlying transports (they don't provide information about connection problems). As such they are transport-specific, and it's a coincidence that both our transports need heartbeats (but it would easily conceivable that they needed *different* heartbeats). That's why I think this should be implemented without patches.

@chrhol can you tell us what you think? If everybody like Tomek's idea, I'll gladly help in implementing it

**Comment by tomalec** [comment]
@joozek78 Could you elaborate more precisely on "technical limitations of underlying transports"?

**Comment by joozek78** [comment]
If those transports provided us with means to know when the connection is broken we wouldn't need to implement the heartbeat at all. Unfortunately they don't provide such capability and can break without us noticing it.

BTW warpech added an important thing - server has no means to push a message over HTTP, so we don't the heartbeat there.

**Comment by tomalec** [comment]
Could you be more specific? What do you mean by "transports"? and about what "problems" and "breaks" we are talking about?

> If those transports provided us with means to know when the connection is broken we wouldn't need to implement the heartbeat at all. Unfortunately they don't provide such capability and can break without us noticing it.

Are you describing the fact that Web Socket does not emit `onerror`, `onclode` event?

**Comment by joozek78** [comment]
I mean that it is possible that server is unable to push a message to client and client is unable to detect it. For example, if a device between client and server malfunctions and ceases to route traffic.

Transports used by puppetjs are HTTP and WS

**Comment by chrhol** [comment]
> @chrhol can you tell us what you think? If everybody like Tomek's idea, I'll gladly help in implementing it

As for which of the two different approaches is more correct, I have no opinon (or knowledge rather :smile:)

Tomeks suggestions have the advantage of being fairly simple. The changes on the server will be minimal and no extra code will be needed, other than not always generate changes (but that is just a simple check).

**Comment by joozek78** [comment]
Okay, it's simpler, so it's better :)

1. I'll send empty patch sequences as heartbeats (`[]`)
1. @chrhol will not refresh any bindings upon receiving an empty sequence

**Comment by chrhol** [comment]
I've pushed the needed changes on the server to develop and pnext now. They should be included in the next nightly build.

**Comment by joozek78** [comment]
The fixes have been pushed to starcounter develop.

* Heartbeat interval is now 60s by default, to avoid reconnection during debugging sessions. You can change it with `ping-interval-s` attribute of `puppet-client`
* Heartbeat doesn't trigger bindings refresh
